In [1]:
import numpy as np 
from simulation import Field, Simulation

In [2]:
num_molecules = 500
molecules = list(range(num_molecules))
# molecules

In [3]:
cell_size = 1
num_rows = 20
num_columns = 20
cells = Field.init_cells(num_rows, num_columns)
# cells

In [4]:
field = Field(num_rows, num_columns,cell_size)
field.clear_cells()
# field._cells

In [5]:
field.clear_cells()
maxX = num_columns * cell_size
maxY = num_rows * cell_size
positions = np.asarray([[i*cell_size - 0.5,i*cell_size + 0.5] for  i in range(-1,num_columns+2)])
# print(positions)
field.place_into_cells(positions)
# field._cells

[ 0  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


In [6]:
positions = np.asarray([[0,0] for  i in range(0,3)])
velocities = np.asarray([[i,0] for  i in range(0,3)])
accelerations = np.asarray([[0,i] for  i in range(0,3)])
h = 0.1
# print(positions)
positions = positions + h * velocities + h**2 /2 * accelerations
# positions

In [7]:
accelerations = np.zeros_like(positions)
# accelerations

In [8]:
i = 2
j = 1
other = field.get_relevant_content(i,j)
# print(other)
# field._cells

In [9]:
from numpy.random import default_rng

SEED = 1234  # this gets executed each time this file is imported
rng = default_rng(seed=SEED)
rng_gen = rng.uniform
init_kwargs = {}
init_kwargs["low"] = [0, 0]
init_kwargs["high"] = [maxX, maxY]

positions = np.empty(shape=(num_molecules,2))
# positions

In [10]:
distribution = "uniform"
simulation = Simulation(num_molecules, num_rows, num_columns, cell_size,distribution)
simulation._positions[:10]

array([[19.53399533,  4.3790623 ],
       [ 7.6039147 ,  1.00993302],
       [18.46492468, 11.59946534],
       [ 5.23384848, 16.67309051],
       [ 6.38194117, 10.74916862],
       [ 2.36182466, 11.49094941],
       [ 4.83532587, 12.43423793],
       [ 6.37067858,  9.73479573],
       [19.2815849 ,  1.37146212],
       [ 5.27299609,  9.78189728]])

In [11]:
for x in range(100): 
    simulation.do_step()
simulation._positions[:10]

19 14
  6 14 19 13  4 15  1 10  5 18  4 11 20  8  7 17  5 13  8  7  6  1 19  5
  5 20  4  7  9  1  4 11  9  2 16 18 20  5 14 14  5 13  1  3 11  9  1 15
 10  1  4  1 16  2  4 17 16 12  2  3  9  9  6 14  1 13  1 13]
[19  6 17  6 10  8 13  9  5  5 10 16  3 13  8 15  3  1 12 11 17  5 14  5
 10  4 18 13 19  4 16 20  1  7  7  1 15  9 14 13  9 17  8 12  4  5 16  3
  1  5 14 16  9 14 12  2  7  7 19 18  8 18 14 10 19 10 13 14 16  3  1  6
 15 17  1 14 12  9 14  5  3  5 10  2 20  5 14  8  5 10  2 10 10 17  8 12
 18 20 13 15 11 18 13 11 12 12  3  8 11  6 17  8 12 17 13  2  2  1 19  4
  9 12  9 10  1 13 13  6 10 17 10 10  5 20  9 11 19 16  6 14  3 12  4 10
  3  8  6 16  1 12  7 13 12  6  7  7  8 12 14 13  7 12  2 11 13  8 10  1
 11  4  9  6 13  9  8 18  2 18 10 17  1  5  6  2  5  3 14 11 16 12 10  5
  8 17  8 19 12 10  6  7 20  3  3  1  5 13  6  5 15 15  3  1  1  4  7 18
 14 17  1  2  1 10 11  1 20 12 10  5 17  3 19 18 11 14  3 20 18 12 11  6
 20  6 17  5 15  6  1 17 16 13 12 18  3  5 13  8 12  8 2

array([[10.        ,  4.        ],
       [ 4.66050339, 17.45384598],
       [18.31640625,  7.74951172],
       [ 8.07568359, 13.88671875],
       [16.13893199, 14.51829386],
       [13.94358397,  5.35414982],
       [12.        , 12.        ],
       [14.        ,  8.        ],
       [ 6.86999512,  1.9234848 ],
       [12.        , 16.        ]])