In [1]:
import numpy as np 
from simulation import Field

In [2]:
num_molecules = 10
molecules = list(range(num_molecules))
molecules

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
cell_size = 1
num_rows = 2
num_columns = 3
cells = Field.init_cells(num_rows, num_columns)
cells

[[[(2, 3)], [(2, 1)], [(2, 2)], [(2, 3)], [(2, 1)]],
 [[(1, 3)], [(1, 1)], [(1, 2)], [(1, 3)], [(1, 1)]],
 [[(2, 3)], [(2, 1)], [(2, 2)], [(2, 3)], [(2, 1)]],
 [[(1, 3)], [(1, 1)], [(1, 2)], [(1, 3)], [(1, 1)]]]

In [4]:
field = Field(num_rows, num_columns,cell_size)
field.clear_cells()
field._cells

[[[], [], [], [], []],
 [[], [], [], [], []],
 [[], [], [], [], []],
 [[], [], [], [], []]]

In [5]:
field.clear_cells()
maxX = num_columns * cell_size

positions = np.asarray([[i*cell_size - 0.5,i*cell_size + 0.5] for  i in range(-1,num_columns+2)])
print(positions)
field.place_into_cells(positions)
field._cells

[[-1.5 -0.5]
 [-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]]


[[[0], [2], [], [0], [2]],
 [[1, 4], [5], [3], [1, 4], [5]],
 [[0], [2], [], [0], [2]],
 [[1, 4], [5], [3], [1, 4], [5]]]

In [6]:
positions = np.asarray([[0,0] for  i in range(0,3)])
velocities = np.asarray([[i,0] for  i in range(0,3)])
accelerations = np.asarray([[0,i] for  i in range(0,3)])
h = 0.1
print(positions)
positions = positions + h * velocities + h**2 /2 * accelerations
positions

[[0 0]
 [0 0]
 [0 0]]


array([[0.   , 0.   ],
       [0.1  , 0.005],
       [0.2  , 0.01 ]])

In [7]:
accelerations = np.zeros_like(positions)
accelerations

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
field.get_relevant_cells(num_rows+1,1)

ValueError: The specified indices i=3, j=1 are invalid.